export const TOSS_EMOJI_BASE = 'https://static.toss.im/2d-emojis/svg';

export function tossEmoji(code: string): string {
  return `${TOSS_EMOJI_BASE}/u${code.toUpperCase()}.svg`;
}

export const TE = {
  house:       '1F3E1',
  camera:      '1F4F8',
  pencil:      '270F',
  people:      '1F465',
  money:       '1F4B5',
  chartBar:    '1F4CA',
  folder:      '1F4C2',
  gear:        '2699',
  piggy:       '1F4B0',
  ledger:      '1F4D2',
  repeat:      '1F501',
  lightning:   '26A1',
  party:       '1F389',
  lock:        '1F512',
  check:       '2705',
  bulb:        '1F4A1',
  gift:        '1F381',
  dog:         '1F436',
  plane:       '2708',
  photoCamera: '1F4F7',
  gamepad:     '1F3AE',
  music:       '1F3B5',
  cake:        '1F370',
  muscle:      '1F4AA',
  plant:       '1F331',
  car:         '1F697',
  art:         '1F3A8',
  phone:       '1F4F1',
  coin:        '1FA99',
  chartUp:     '1F4C8',
  shield:      '1F6E1',
  creditCard:  '1F4B3',
  briefcase:   '1F4BC',
  receipt:     '1F9FE',
  sparkles:    '2728',
  home2:       '1F3E0',
  subway:      '1F687',
  hospital:    '1F4CA',
  bag:         '1F6CD',
  clapperboard:'1F3AC',
  books:       '1F4DA',
  tvSet:       '1F4FA',
  cyclone:     '1F300',
  mailbox:     '1F4ED',
  search:      '1F50D',
  bank:        '1F3E6',
  trash:       '1F5D1',
  link:        '1F517',
};

export const CATEGORY_ICON_CHOICES = [
  { id: 'gift',        code: TE.gift },
  { id: 'dog',         code: TE.dog },
  { id: 'plane',       code: TE.plane },
  { id: 'camera',      code: TE.photoCamera },
  { id: 'game',        code: TE.gamepad },
  { id: 'music',       code: TE.music },
  { id: 'cake',        code: TE.cake },
  { id: 'muscle',      code: TE.muscle },
  { id: 'plant',       code: TE.plant },
  { id: 'car',         code: TE.car },
  { id: 'art',         code: TE.art },
  { id: 'phone',       code: TE.phone },
];
