import { MigrationInterface, QueryRunner } from "typeorm";

export class FullSchema1774071266577 implements MigrationInterface {
    name = 'FullSchema1774071266577'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."operating_settings_type_enum" AS ENUM('estimate', 'construction')`);
        await queryRunner.query(`CREATE TABLE "operating_settings" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "public"."operating_settings_type_enum" NOT NULL, "available_days" text NOT NULL, "start_time" character varying(10) NOT NULL, "end_time" character varying(10) NOT NULL, "slot_duration" integer NOT NULL DEFAULT '60', CONSTRAINT "UQ_ad47f98f60d51ed9c4142c70ecc" UNIQUE ("type"), CONSTRAINT "PK_9956fd4dceff7964574ad985320" PRIMARY KEY ("id")); COMMENT ON COLUMN "operating_settings"."createdAt" IS '생성일시'; COMMENT ON COLUMN "operating_settings"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "date" date NOT NULL, "reason" character varying(200) NOT NULL, CONSTRAINT "UQ_40dfddee0c0d7125c767d8962b1" UNIQUE ("date"), CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id")); COMMENT ON COLUMN "holidays"."createdAt" IS '생성일시'; COMMENT ON COLUMN "holidays"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_link_type_enum" AS ENUM('external', 'internal')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying(100) NOT NULL, "subtitle" character varying(200), "icon_id" integer NOT NULL, "icon_bg_color" character varying(10) NOT NULL, "icon_color" character varying(10) NOT NULL, "link_url" character varying, "link_type" "public"."promotions_link_type_enum" NOT NULL DEFAULT 'external', "start_date" date, "end_date" date, "click_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id")); COMMENT ON COLUMN "promotions"."createdAt" IS '생성일시'; COMMENT ON COLUMN "promotions"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."icons_type_enum" AS ENUM('FILL', 'MONO', 'COLOR')`);
        await queryRunner.query(`CREATE TABLE "icons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(200) NOT NULL, "type" "public"."icons_type_enum" NOT NULL DEFAULT 'MONO', CONSTRAINT "UQ_fd1af68b0932014529d26096d33" UNIQUE ("name"), CONSTRAINT "PK_7d32565ab060c67427b635607de" PRIMARY KEY ("id")); COMMENT ON COLUMN "icons"."createdAt" IS '생성일시'; COMMENT ON COLUMN "icons"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."districts_level_enum" AS ENUM('SIDO', 'SIGUNGU', 'EUPMYEONDONG')`);
        await queryRunner.query(`CREATE TABLE "districts" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying(10) NOT NULL, "fullName" character varying(200) NOT NULL, "name" character varying(100) NOT NULL, "level" "public"."districts_level_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isAbandoned" boolean NOT NULL DEFAULT false, "parent_id" integer, CONSTRAINT "UQ_8e9d73424149b43b38244f75528" UNIQUE ("code"), CONSTRAINT "PK_972a72ff4e3bea5c7f43a2b98af" PRIMARY KEY ("id")); COMMENT ON COLUMN "districts"."createdAt" IS '생성일시'; COMMENT ON COLUMN "districts"."updatedAt" IS '수정일시'; COMMENT ON COLUMN "districts"."code" IS '법정동 코드 (10자리)'; COMMENT ON COLUMN "districts"."fullName" IS '행정구역 전체 이름'; COMMENT ON COLUMN "districts"."name" IS '행정구역 단일 이름'; COMMENT ON COLUMN "districts"."level" IS '행정구역 레벨 (SIDO: 시/도, SIGUNGU: 시/군/구, EUPMYEONDONG: 읍/면/동)'; COMMENT ON COLUMN "districts"."isActive" IS '활성화 여부'; COMMENT ON COLUMN "districts"."isAbandoned" IS '폐지 여부 (항상 false, 폐지된 구역은 DB에 저장하지 않음)'; COMMENT ON COLUMN "districts"."parent_id" IS '상위 행정구역 ID'`);
        await queryRunner.query(`CREATE INDEX "IDX_8669f92aa038020a96d2a493ae" ON "districts" ("level", "parent_id", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_b930715093f604059cf72b32b5" ON "districts" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_592cda313be28fb73f688e489a" ON "districts" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc2771c86e32d7668e03fe4c86" ON "districts" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e9d73424149b43b38244f7552" ON "districts" ("code") `);
        await queryRunner.query(`CREATE TABLE "service_regions" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "service_id" integer NOT NULL, "district_id" integer NOT NULL, "estimate_fee" numeric(10,0) NOT NULL DEFAULT '0', CONSTRAINT "UQ_e8c464f8b8a6b23dce64adadefe" UNIQUE ("service_id", "district_id"), CONSTRAINT "PK_c7b0e3d6e5a73c2b397851445de" PRIMARY KEY ("id")); COMMENT ON COLUMN "service_regions"."createdAt" IS '생성일시'; COMMENT ON COLUMN "service_regions"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."service_schedules_estimate_schedule_mode_enum" AS ENUM('global', 'weekdays', 'weekends', 'everyday', 'custom', 'everyday_except')`);
        await queryRunner.query(`CREATE TYPE "public"."service_schedules_construction_schedule_mode_enum" AS ENUM('global', 'weekdays', 'weekends', 'everyday', 'custom', 'everyday_except')`);
        await queryRunner.query(`CREATE TABLE "service_schedules" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "service_id" integer NOT NULL, "estimate_schedule_mode" "public"."service_schedules_estimate_schedule_mode_enum" NOT NULL DEFAULT 'global', "estimate_available_days" text, "estimate_start_time" character varying(10), "estimate_end_time" character varying(10), "estimate_slot_duration" integer, "construction_schedule_mode" "public"."service_schedules_construction_schedule_mode_enum" NOT NULL DEFAULT 'global', "construction_available_days" text, "construction_start_time" character varying(10), "construction_end_time" character varying(10), "construction_slot_duration" integer, "booking_period_months" integer NOT NULL DEFAULT '3', CONSTRAINT "UQ_0224c5a9edcab036cc095991852" UNIQUE ("service_id"), CONSTRAINT "REL_0224c5a9edcab036cc09599185" UNIQUE ("service_id"), CONSTRAINT "PK_64aec60a9993270f6921b8f524d" PRIMARY KEY ("id")); COMMENT ON COLUMN "service_schedules"."createdAt" IS '생성일시'; COMMENT ON COLUMN "service_schedules"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0224c5a9edcab036cc09599185" ON "service_schedules" ("service_id") `);
        await queryRunner.query(`CREATE TABLE "service_holidays" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "service_id" integer NOT NULL, "date" date NOT NULL, "reason" character varying(200) NOT NULL, CONSTRAINT "PK_ff79bc36431c319a49ca171e8d2" PRIMARY KEY ("id")); COMMENT ON COLUMN "service_holidays"."createdAt" IS '생성일시'; COMMENT ON COLUMN "service_holidays"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_486038b9f32a7c2b1174a53f2e" ON "service_holidays" ("service_id", "date") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying(100) NOT NULL, "description" text NOT NULL, "icon_id" integer NOT NULL, "icon_bg_color" character varying(10), "icon_color" character varying(10), "duration" character varying(50) NOT NULL, "requires_time_selection" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id")); COMMENT ON COLUMN "services"."createdAt" IS '생성일시'; COMMENT ON COLUMN "services"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "uuid" uuid NOT NULL, "toss_user_id" character varying, "name" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255), "refresh_token" text, CONSTRAINT "UQ_a41cc8fde9ac3d9bcb91412c596" UNIQUE ("uuid"), CONSTRAINT "UQ_43dad740db729b620720909c9a2" UNIQUE ("toss_user_id"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")); COMMENT ON COLUMN "customers"."createdAt" IS '생성일시'; COMMENT ON COLUMN "customers"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."reservations_status_enum" AS ENUM('pending', 'confirmed', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "reservations" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "reservation_number" character varying(20) NOT NULL, "customer_id" integer NOT NULL, "service_id" integer NOT NULL, "estimate_date" date NOT NULL, "estimate_time" character varying(10) NOT NULL, "construction_date" date, "construction_time" character varying(10), "confirmed_at" TIMESTAMP, "address" character varying(500) NOT NULL, "detail_address" character varying(200) NOT NULL, "customer_name" character varying(100) NOT NULL, "customer_phone" character varying(20) NOT NULL, "memo" text, "photos" text, "status" "public"."reservations_status_enum" NOT NULL DEFAULT 'pending', "cancelled_at" TIMESTAMP, CONSTRAINT "UQ_ec7bddfb31ba19db3c085f5bd2b" UNIQUE ("reservation_number"), CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id")); COMMENT ON COLUMN "reservations"."createdAt" IS '생성일시'; COMMENT ON COLUMN "reservations"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "reservation_id" integer NOT NULL, "customer_id" integer NOT NULL, "service_id" integer NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "images" text, CONSTRAINT "UQ_f63ab9c649a65b065e866f505db" UNIQUE ("reservation_id"), CONSTRAINT "REL_f63ab9c649a65b065e866f505d" UNIQUE ("reservation_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id")); COMMENT ON COLUMN "reviews"."createdAt" IS '생성일시'; COMMENT ON COLUMN "reviews"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "portfolios" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "category" character varying(50) NOT NULL, "project_name" character varying(200) NOT NULL, "client" character varying(100), "duration" character varying(50) NOT NULL, "description" text NOT NULL, "detailed_description" text NOT NULL, "images" text NOT NULL, "tags" text, "service_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_488aa6e9b219d1d9087126871ae" PRIMARY KEY ("id")); COMMENT ON COLUMN "portfolios"."createdAt" IS '생성일시'; COMMENT ON COLUMN "portfolios"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "cutting_pieces" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "project_id" integer NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "label" character varying(100), "sort_order" integer NOT NULL DEFAULT '0', "is_completed" boolean NOT NULL DEFAULT false, "fixed_position" jsonb, CONSTRAINT "PK_82f1fceaaf227f12465723db0f8" PRIMARY KEY ("id")); COMMENT ON COLUMN "cutting_pieces"."createdAt" IS '생성일시'; COMMENT ON COLUMN "cutting_pieces"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "cutting_projects" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(200) NOT NULL, "film_id" integer NOT NULL, "allow_rotation" boolean NOT NULL DEFAULT true, "waste_percentage" numeric(5,2), "used_length" integer, "packing_result" jsonb, CONSTRAINT "PK_c046c14726da5b5ecae18bc7ed5" PRIMARY KEY ("id")); COMMENT ON COLUMN "cutting_projects"."createdAt" IS '생성일시'; COMMENT ON COLUMN "cutting_projects"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TABLE "films" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "width" integer NOT NULL DEFAULT '1220', "length" integer NOT NULL DEFAULT '60000', "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_697487ada088902377482c970d1" PRIMARY KEY ("id")); COMMENT ON COLUMN "films"."createdAt" IS '생성일시'; COMMENT ON COLUMN "films"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_status_enum" AS ENUM('active', 'inactive', 'invited', 'suspended')`);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_role_enum" AS ENUM('superadmin', 'admin', 'manager', 'cashier')`);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying NOT NULL, "phone_number" character varying(20), "status" "public"."admin_users_status_enum" NOT NULL DEFAULT 'invited', "role" "public"."admin_users_role_enum" NOT NULL DEFAULT 'cashier', "last_login_at" TIMESTAMP, CONSTRAINT "UQ_d612cedca25f4c7d26e74f58d15" UNIQUE ("uuid"), CONSTRAINT "UQ_2873882c38e8c07d98cb64f962d" UNIQUE ("username"), CONSTRAINT "UQ_dcd0c8a4b10af9c986e510b9ecc" UNIQUE ("email"), CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id")); COMMENT ON COLUMN "admin_users"."createdAt" IS '생성일시'; COMMENT ON COLUMN "admin_users"."updatedAt" IS '수정일시'`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_228b5ade572051f5c05920dcf1b" FOREIGN KEY ("icon_id") REFERENCES "icons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "districts" ADD CONSTRAINT "FK_dc2771c86e32d7668e03fe4c864" FOREIGN KEY ("parent_id") REFERENCES "districts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_regions" ADD CONSTRAINT "FK_3b46634cfda7c32295bce97acfa" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_regions" ADD CONSTRAINT "FK_eab85ab85192926ff46d5a933a5" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_schedules" ADD CONSTRAINT "FK_0224c5a9edcab036cc095991852" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_holidays" ADD CONSTRAINT "FK_8dbe8fcbf96ef68fbe4f175842c" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_6a1d7a4fce5efcc259bff6663c4" FOREIGN KEY ("icon_id") REFERENCES "icons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_f63cb79a34cdf2d47ab23f31a8b" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_f9a66ac5e3a797ee7d588334c18" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_f63ab9c649a65b065e866f505db" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6587db79174d07150fde1f1a4d6" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_e95656a473f1c3d38e995bf906b" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cutting_pieces" ADD CONSTRAINT "FK_168bbc094403ce333840f815385" FOREIGN KEY ("project_id") REFERENCES "cutting_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cutting_projects" ADD CONSTRAINT "FK_583863671e4cc5e211a0f0c43d8" FOREIGN KEY ("film_id") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cutting_projects" DROP CONSTRAINT "FK_583863671e4cc5e211a0f0c43d8"`);
        await queryRunner.query(`ALTER TABLE "cutting_pieces" DROP CONSTRAINT "FK_168bbc094403ce333840f815385"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_e95656a473f1c3d38e995bf906b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6587db79174d07150fde1f1a4d6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_f63ab9c649a65b065e866f505db"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_f9a66ac5e3a797ee7d588334c18"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_f63cb79a34cdf2d47ab23f31a8b"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_6a1d7a4fce5efcc259bff6663c4"`);
        await queryRunner.query(`ALTER TABLE "service_holidays" DROP CONSTRAINT "FK_8dbe8fcbf96ef68fbe4f175842c"`);
        await queryRunner.query(`ALTER TABLE "service_schedules" DROP CONSTRAINT "FK_0224c5a9edcab036cc095991852"`);
        await queryRunner.query(`ALTER TABLE "service_regions" DROP CONSTRAINT "FK_eab85ab85192926ff46d5a933a5"`);
        await queryRunner.query(`ALTER TABLE "service_regions" DROP CONSTRAINT "FK_3b46634cfda7c32295bce97acfa"`);
        await queryRunner.query(`ALTER TABLE "districts" DROP CONSTRAINT "FK_dc2771c86e32d7668e03fe4c864"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_228b5ade572051f5c05920dcf1b"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_status_enum"`);
        await queryRunner.query(`DROP TABLE "films"`);
        await queryRunner.query(`DROP TABLE "cutting_projects"`);
        await queryRunner.query(`DROP TABLE "cutting_pieces"`);
        await queryRunner.query(`DROP TABLE "portfolios"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "reservations"`);
        await queryRunner.query(`DROP TYPE "public"."reservations_status_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_486038b9f32a7c2b1174a53f2e"`);
        await queryRunner.query(`DROP TABLE "service_holidays"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0224c5a9edcab036cc09599185"`);
        await queryRunner.query(`DROP TABLE "service_schedules"`);
        await queryRunner.query(`DROP TYPE "public"."service_schedules_construction_schedule_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."service_schedules_estimate_schedule_mode_enum"`);
        await queryRunner.query(`DROP TABLE "service_regions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e9d73424149b43b38244f7552"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc2771c86e32d7668e03fe4c86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_592cda313be28fb73f688e489a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b930715093f604059cf72b32b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8669f92aa038020a96d2a493ae"`);
        await queryRunner.query(`DROP TABLE "districts"`);
        await queryRunner.query(`DROP TYPE "public"."districts_level_enum"`);
        await queryRunner.query(`DROP TABLE "icons"`);
        await queryRunner.query(`DROP TYPE "public"."icons_type_enum"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_link_type_enum"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP TABLE "operating_settings"`);
        await queryRunner.query(`DROP TYPE "public"."operating_settings_type_enum"`);
    }

}
