import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Transaction } from './entities/transaction.entity';
import { CreateTransactionDto } from './dto/request/create-transaction.dto';
import { SearchTransactionsDto } from './dto/request/search-transactions.dto';

@Injectable()
export class TransactionsService {
  constructor(
    @InjectRepository(Transaction)
    private readonly txRepo: Repository<Transaction>,
  ) {}

  async findRecent(householdId: number, limit = 10): Promise<Transaction[]> {
    return this.txRepo.find({
      where: { householdId },
      order: { date: 'DESC', createdAt: 'DESC' },
      take: limit,
    });
  }

  async search(householdId: number, dto: SearchTransactionsDto): Promise<{ data: Transaction[]; total: number }> {
    const page = dto.page ?? 1;
    const limit = dto.limit ?? 50;
    const qb = this.txRepo.createQueryBuilder('tx').where('tx.householdId = :householdId', { householdId });

    if (dto.from) qb.andWhere('tx.date >= :from', { from: dto.from });
    if (dto.to) qb.andWhere('tx.date <= :to', { to: dto.to });
    if (dto.type) qb.andWhere('tx.type = :type', { type: dto.type });
    if (dto.categoryId) qb.andWhere('tx.categoryId = :categoryId', { categoryId: dto.categoryId });
    if (dto.assetId) qb.andWhere('(tx.fromAssetId = :assetId OR tx.toAssetId = :assetId)', { assetId: dto.assetId });
    if (dto.keyword) qb.andWhere('(tx.title ILIKE :kw OR tx.memo ILIKE :kw)', { kw: `%${dto.keyword}%` });
    if (dto.includeAutoGenerated === false) qb.andWhere('tx.autoGenerated = false');

    qb.orderBy('tx.date', 'DESC')
      .addOrderBy('tx.createdAt', 'DESC')
      .skip((page - 1) * limit)
      .take(limit);

    const [data, total] = await qb.getManyAndCount();
    return { data, total };
  }

  async findOne(id: number): Promise<Transaction> {
    const tx = await this.txRepo.findOne({ where: { id } });
    if (!tx) throw new NotFoundException('거래를 찾을 수 없습니다.');
    return tx;
  }

  async create(householdId: number, dto: CreateTransactionDto, userId: number): Promise<Transaction> {
    const tx = this.txRepo.create({ ...dto, householdId, createdByUserId: userId });
    return this.txRepo.save(tx);
  }

  async update(id: number, dto: Partial<CreateTransactionDto>): Promise<Transaction> {
    const tx = await this.findOne(id);
    Object.assign(tx, dto);
    return this.txRepo.save(tx);
  }

  async delete(id: number): Promise<void> {
    const tx = await this.findOne(id);
    await this.txRepo.remove(tx);
  }
}
