import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { RecurringTransaction, RecurringFrequency } from './entities/recurring-transaction.entity';
import { Transaction } from '../transactions/entities/transaction.entity';
import { CreateRecurringDto } from './dto/request/create-recurring.dto';

@Injectable()
export class RecurringTransactionsService {
  constructor(
    @InjectRepository(RecurringTransaction)
    private readonly recurringRepo: Repository<RecurringTransaction>,
    @InjectRepository(Transaction)
    private readonly txRepo: Repository<Transaction>,
  ) {}

  async findByHousehold(householdId: number): Promise<RecurringTransaction[]> {
    return this.recurringRepo.find({ where: { householdId }, order: { createdAt: 'ASC' } });
  }

  async findOne(id: number): Promise<RecurringTransaction> {
    const r = await this.recurringRepo.findOne({ where: { id } });
    if (!r) throw new NotFoundException('정기거래를 찾을 수 없습니다.');
    return r;
  }

  async create(householdId: number, dto: CreateRecurringDto): Promise<RecurringTransaction> {
    const r = this.recurringRepo.create({ ...dto, householdId, active: true });
    return this.recurringRepo.save(r);
  }

  async update(id: number, dto: Partial<CreateRecurringDto>): Promise<RecurringTransaction> {
    const r = await this.findOne(id);
    Object.assign(r, dto);
    return this.recurringRepo.save(r);
  }

  async toggle(id: number): Promise<RecurringTransaction> {
    const r = await this.findOne(id);
    r.active = !r.active;
    return this.recurringRepo.save(r);
  }

  async delete(id: number): Promise<void> {
    const r = await this.findOne(id);
    await this.recurringRepo.remove(r);
  }

  async runDailyAll(): Promise<void> {
    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    const todayDay = today.getDate();
    const todayMonth = today.getMonth() + 1;

    const actives = await this.recurringRepo.find({ where: { active: true } });

    for (const r of actives) {
      try {
        if (r.lastRunDate === todayStr) continue;
        if (r.endDate && r.endDate < todayStr) continue;
        if (r.startDate > todayStr) continue;

        const shouldRun =
          r.frequency === RecurringFrequency.MONTHLY
            ? r.dayOfMonth === todayDay
            : r.dayOfMonth === todayDay && r.monthOfYear === todayMonth;

        if (!shouldRun) continue;

        await this.generateTransaction(r);
        r.lastRunDate = todayStr;
        await this.recurringRepo.save(r);
      } catch (_) {
        // 개별 실패가 전체 cron 중단 방지
      }
    }
  }

  private async generateTransaction(r: RecurringTransaction): Promise<Transaction> {
    const today = new Date().toISOString().split('T')[0];
    const tx = this.txRepo.create({
      householdId: r.householdId,
      date: today,
      type: r.type,
      amount: r.amount,
      categoryId: r.categoryId,
      fromAssetId: r.fromAssetId,
      toAssetId: r.toAssetId,
      title: r.title,
      memo: r.memo,
      recurringTemplateId: r.id,
      autoGenerated: true,
    });
    return this.txRepo.save(tx);
  }
}
