import { Column, Entity, Index } from 'typeorm';
import { BaseEntity } from '@common/entities/base.entity';
import { CostType } from '@ad/modules/categories/entities/category.entity';

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

@Entity('transactions', { schema: 'ad' })
@Index(['householdId', 'date'])
// 정기거래 cron이 같은 날짜에 같은 정기거래를 두 번 만들지 못하게 막는 마지막 방어선
// (2026-09-16 cluster 중복 발화로 실제 3중복 발생 — 코드 가드가 뚫려도 DB에서 막음).
// 수동 입력 거래는 recurringTemplateId가 NULL이라 where절로 제외(NULL끼리는 유니크 검사 대상 아님이지만 명시).
@Index(['recurringTemplateId', 'date'], { unique: true, where: '"recurring_template_id" IS NOT NULL' })
export class Transaction extends BaseEntity {
  @Column({ name: 'household_id' })
  householdId: number;

  @Column({ type: 'date' })
  date: string;

  @Column({ type: 'enum', enum: TransactionType })
  type: TransactionType;

  @Column({ type: 'decimal', precision: 20, scale: 2 })
  amount: number;

  @Column({ name: 'category_id', nullable: true })
  categoryId: number;

  @Column({ name: 'cost_type', type: 'enum', enum: CostType, nullable: true })
  costType?: CostType | null;

  @Column({ name: 'from_asset_id', nullable: true })
  fromAssetId: number;

  @Column({ name: 'to_asset_id', nullable: true })
  toAssetId: number;

  @Column({ length: 200, nullable: true })
  title: string;

  @Column({ type: 'text', nullable: true })
  memo: string;

  @Column({ type: 'simple-array', nullable: true })
  tags: string[];

  @Column({ type: 'jsonb', nullable: true })
  attachments: object[];

  @Column({ name: 'recurring_template_id', nullable: true })
  recurringTemplateId: number;

  @Column({ name: 'auto_generated', default: false })
  autoGenerated: boolean;

  @Column({ name: 'created_by_user_id', nullable: true })
  createdByUserId: number;
}
