/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _IndexRoute } from '../pages/';
import { Route as _AuthOnboardingRoute } from '../pages/auth/onboarding';
import { Route as _AuthJoinRoute } from '../pages/auth/join';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/auth/onboarding': (typeof _AuthOnboardingRoute)['_inputType'];
    '/auth/join': (typeof _AuthJoinRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/auth/onboarding': (typeof _AuthOnboardingRoute)['_outputType'];
    '/auth/join': (typeof _AuthJoinRoute)['_outputType'];
  }
}
